# Generated by Django 6.0 on 2025-12-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thekua', '0002_category_pendinguser_user_profile_pic_address_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='starting_from',
        ),
    ]
