# Generated by Django 6.0.1 on 2026-01-28 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thekua', '0002_order_coupon_order_discount_price_order_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='thekua.order'),
        ),
    ]
