# Generated by Django 6.0.1 on 2026-01-29 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thekua', '0003_reviews_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('order', 'Order Issue'), ('product', 'Product Issue'), ('payment', 'Payment Issue'), ('delivery', 'Delivery Issue'), ('general', 'General Query')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ai_handling', 'AI Handling'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='ai_handling', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thekua.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ai', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='ticketimages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='thekua.supportticket')),
            ],
        ),
    ]
