# Generated by Django 6.0.1 on 2026-01-29 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thekua', '0004_supportticket_supportmessage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('product', 'user', 'order')},
        ),
    ]
