# Generated by Django 6.0 on 2026-01-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thekua', '0006_storeprofile_alter_product_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeprofile',
            old_name='logo',
            new_name='profile',
        ),
    ]
