# Generated by Django 6.0 on 2026-01-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thekua', '0007_rename_logo_storeprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='fssai_number',
            field=models.CharField(blank=True, help_text='FSSAI License Number', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GSTIN (15 characters)', max_length=15, null=True),
        ),
    ]
