# Generated by Django 6.0 on 2025-12-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thekua', '0008_product_slug_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategories/'),
        ),
    ]
