# Generated by Django 6.0 on 2025-12-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thekua', '0009_subcategory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
