name: Ecommerce Django CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

          cd ${{ secrets.PROJECT_PATH }}

          git pull origin main

          ../venv/bin/pip install -r requirements.txt
          ../venv/bin/python manage.py makemigrations --noinput
          ../venv/bin/python manage.py migrate --noinput
          ../venv/bin/python manage.py collectstatic --noinput

          sudo systemctl restart gunicorn
          sudo systemctl reload nginx

          EOF
